# Generated by Django 4.2.2 on 2023-07-15 22:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
